### ISSUE TITLE
Wrong count number or sometimes crashes on http://www.zdnet.com/

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AddonTestHarness#3]
On http://www.zdnet.com/ 
Sometimes it will report ad count is 0 (instead of the actual number 2 showing on the ADN badge).
Sometimes it crashes with the following error:

```
Loading 1 URL(s)
May 18, 2015 7:59:18 PM org.openqa.selenium.support.ui.ExpectedConditions findElement
WARNING: WebDriverException thrown by findElement(By.id: adnauseam-count)
org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Command duration or timeout: 73.86 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Cyrus-MacBook-Air.local', ip: '192.168.31.219', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.2, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: d764c6c2-e45d-4b44-a773-b41803421e8c
*** Element info: {Using=id, value=adnauseam-count}
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:393)
    at org.openqa.selenium.By$ById.findElement(By.java:214)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
    at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
    at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
    at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
    at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:103)
    at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
    at ath.adnauseum.AdNauseamPageVisitor.getCount(AdNauseamPageVisitor.java:144)
    at ath.adnauseum.AdNauseamPageVisitor.go(AdNauseamPageVisitor.java:213)
    at ath.adnauseum.AdNauseamPageVisitor.go(AdNauseamPageVisitor.java:199)
    at ath.adnauseum.AdNauseamPageVisitor.main(AdNauseamPageVisitor.java:231)
Caused by: org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Cyrus-MacBook-Air.local', ip: '192.168.31.219', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
    at <anonymous class>.<anonymous method>(http://zdnet2.cbsistatic.com/fly/336-fly/bundles/zdnetjs/js/libs/bugsnag.js:1)

Exception in thread "main" org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Command duration or timeout: 73.86 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Cyrus-MacBook-Air.local', ip: '192.168.31.219', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=37.0.2, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: d764c6c2-e45d-4b44-a773-b41803421e8c
*** Element info: {Using=id, value=adnauseam-count}
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:393)
    at org.openqa.selenium.By$ById.findElement(By.java:214)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
    at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
    at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
    at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
    at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:103)
    at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
    at ath.adnauseum.AdNauseamPageVisitor.getCount(AdNauseamPageVisitor.java:144)
    at ath.adnauseum.AdNauseamPageVisitor.go(AdNauseamPageVisitor.java:213)
    at ath.adnauseum.AdNauseamPageVisitor.go(AdNauseamPageVisitor.java:199)
    at ath.adnauseum.AdNauseamPageVisitor.main(AdNauseamPageVisitor.java:231)
Caused by: org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'Cyrus-MacBook-Air.local', ip: '192.168.31.219', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
    at <anonymous class>.<anonymous method>(http://zdnet2.cbsistatic.com/fly/336-fly/bundles/zdnetjs/js/libs/bugsnag.js:1)
```

Website screenshot:
![screen shot 2015-05-18 at 7 59 42 pm](https://cloud.githubusercontent.com/assets/2461812/7680410/d905435c-fd98-11e4-9519-78ccb44c6f60.png)

**Comment by dhowe** [comment]
This is fixed to the extent that it shouldn't crash on such cases, however I'm not sure what the actual cause is.
Please verify that you can run the full set of tests now, though you will likely get 0 for ZDNET and similar...

**Comment by dhowe** [comment]
ps. please move all tickets from here to the adn project. thanks

**Comment by CyrusSUEN** [comment]
> Please verify that you can run the full set of tests now

Took around 1.5 to 2 hrs to run the full set ~83 URLs and updated the spreadsheet.
I removed this URL from the list temporarily for running the script since the script couldn't complete with the above error.

> ps. please move all tickets from here to the adn project. thanks

OK. Please close this one and I will copy this ticket over ADN.

**Comment by CyrusSUEN** [comment]
Moved ticket to https://github.com/dhowe/AdNauseam/issues/325
Closed
